<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ArrowLeft, GripVertical, MapPin, Pencil, Plus, Save, Search, Trash2, X } from 'lucide-vue-next'
import { useRoute, useRouter } from 'vue-router'
import { deleteCourse, getCourse, updateCourse } from '../api/courses'
import { getLocations } from '../api/locations'
import StatePanel from '../components/common/StatePanel.vue'

const route = useRoute(); const router = useRouter()
const course = ref(null); const loading = ref(true); const error = ref(''); const editing = ref(false); const saving = ref(false); const deleting = ref(false); const deleteOpen = ref(false); const deletePassword = ref(''); const formError = ref('')
const form = reactive({ title: '', description: '', password: '', locations: [] })
const locationQuery = ref(''); const locationResults = ref([]); const locationSearching = ref(false)
let dragIndex = null
function fillForm(value) { form.title = value.title; form.description = value.description; form.password = ''; form.locations = [...value.locations] }
async function load() { loading.value = true; error.value = ''; try { course.value = await getCourse(route.params.id); fillForm(course.value) } catch (err) { error.value = err.message } finally { loading.value = false } }
function beginDrag(event, index) { dragIndex = index; event.dataTransfer.effectAllowed = 'move' }
function reorder(target) { if (dragIndex == null || dragIndex === target) return; const [item] = form.locations.splice(dragIndex, 1); form.locations.splice(target, 0, item); dragIndex = target }
async function searchLocations() { const keyword = locationQuery.value.trim(); if (!keyword) return; locationSearching.value = true; try { locationResults.value = (await getLocations({ search: keyword, size: 8 })).items.filter((item) => !form.locations.some((place) => place.id === item.id)) } catch (err) { formError.value = err.message } finally { locationSearching.value = false } }
function addLocation(place) { form.locations.push(place); locationResults.value = []; locationQuery.value = '' }
async function save() { formError.value = ''; saving.value = true; try { course.value = await updateCourse(course.value.id, { title: form.title.trim(), description: form.description.trim(), password: form.password, location_ids: form.locations.map((item) => item.id) }); fillForm(course.value); editing.value = false } catch (err) { formError.value = err.status === 403 ? '비밀번호가 일치하지 않습니다.' : err.message } finally { saving.value = false } }
async function remove() { formError.value = ''; deleting.value = true; try { await deleteCourse(course.value.id, deletePassword.value); router.push('/courses') } catch (err) { formError.value = err.status === 403 ? '비밀번호가 일치하지 않습니다.' : err.message } finally { deleting.value = false } }
onMounted(load)
</script>

<template>
  <div class="page course-page container"><RouterLink class="back-link" to="/courses"><ArrowLeft :size="17" />코스 목록</RouterLink><StatePanel v-if="loading" type="loading" title="코스를 불러오고 있어요" /><StatePanel v-else-if="error" type="error" title="코스를 찾지 못했어요" :message="error" @retry="load" />
    <template v-else-if="course"><header class="course-heading"><div><p class="eyebrow">LOCAL ROUTE</p><h1>{{ course.title }}</h1><p>{{ course.description }}</p></div><div><button class="button secondary" type="button" @click="editing = !editing; fillForm(course)"><Pencil :size="16" />수정</button><button class="button danger" type="button" @click="deleteOpen = true"><Trash2 :size="16" />삭제</button></div></header>
      <form v-if="editing" class="edit-panel panel" @submit.prevent="save"><div class="field"><label>코스 이름</label><input v-model="form.title" class="input" maxlength="200" required /></div><div class="field"><label>설명</label><textarea v-model="form.description" class="textarea" maxlength="10000" required></textarea></div><div class="field"><label>장소 추가</label><div class="place-search"><Search :size="17" /><input v-model="locationQuery" placeholder="추가할 장소 검색" @keydown.enter.prevent="searchLocations" /><button type="button" @click="searchLocations">검색</button></div><div v-if="locationResults.length" class="search-options"><button v-for="place in locationResults" :key="place.id" type="button" @click="addLocation(place)"><Plus :size="15" />{{ place.title }}</button></div></div><div class="field"><label>관리 비밀번호</label><input v-model="form.password" class="input" type="password" required autocomplete="current-password" /></div><p v-if="formError" class="form-error">{{ formError }}</p><button class="button primary" type="submit" :disabled="saving || form.locations.length < 2"><Save :size="16" />{{ saving ? '저장 중...' : '변경 저장' }}</button></form>
      <section class="route-list"><div class="section-head"><h2>방문 spot</h2><span>{{ (editing ? form.locations : course.locations).length }}곳</span></div><ol><li v-for="(place,index) in (editing ? form.locations : course.locations)" :key="place.id" :draggable="editing" @dragstart="beginDrag($event,index)" @dragover.prevent="editing && reorder(index)" @dragend="dragIndex = null"><GripVertical v-if="editing" :size="18" /><b>{{ index + 1 }}</b><RouterLink :to="`/locations/${place.id}`"><strong>{{ place.title }}</strong><span><MapPin :size="13" />{{ place.address || '주소 정보 없음' }}</span></RouterLink><button v-if="editing" type="button" @click="form.locations.splice(index,1)"><X :size="16" /></button></li></ol></section>
      <div v-if="deleteOpen" class="modal-backdrop" @click.self="deleteOpen = false"><form class="delete-modal panel" @submit.prevent="remove"><h2>코스를 삭제할까요?</h2><p>저장할 때 입력한 관리 비밀번호가 필요합니다.</p><input v-model="deletePassword" class="input" type="password" required autofocus /><p v-if="formError" class="form-error">{{ formError }}</p><div><button class="button ghost" type="button" @click="deleteOpen = false">취소</button><button class="button danger" type="submit" :disabled="deleting">{{ deleting ? '삭제 중...' : '삭제' }}</button></div></form></div>
    </template>
  </div>
</template>

<style scoped>
.course-page { max-width: 920px; }.back-link { display: inline-flex; align-items: center; gap: 5px; margin-bottom: 22px; color: var(--color-muted); font-size: 13px; font-weight: 700; }.course-heading { display: flex; align-items: end; justify-content: space-between; gap: 24px; margin-bottom: 34px; }.course-heading h1 { margin: 5px 0 10px; font-size: 42px; }.course-heading p { max-width: 650px; margin: 0; color: var(--color-muted); line-height: 1.7; }.course-heading > div:last-child { display: flex; gap: 7px; }.edit-panel { display: grid; gap: 18px; margin-bottom: 25px; padding: 24px; }.edit-panel .textarea { min-height: 120px; }.place-search { display: flex; align-items: center; gap: 7px; }.place-search input { min-width: 0; flex: 1; height: 42px; padding: 0 10px; border: 1px solid var(--color-line); border-radius: 6px; }.place-search button { height: 42px; border: 0; color: var(--color-primary-dark); background: var(--color-primary-soft); font-weight: 700; }.search-options { display: flex; flex-wrap: wrap; gap: 5px; }.search-options button { display: flex; align-items: center; gap: 4px; padding: 7px 9px; border: 1px solid var(--color-line); border-radius: 999px; background: #fff; font-size: 10px; }.form-error { margin: 0; color: var(--color-danger); font-size: 12px; }.section-head { display: flex; align-items: center; justify-content: space-between; }.section-head span { color: var(--color-muted); }.route-list ol { display: grid; gap: 9px; padding: 0; list-style: none; }.route-list li { display: flex; align-items: center; gap: 12px; padding: 14px; border: 1px solid var(--color-line); border-radius: 8px; background: #fff; }.route-list li > b { display: grid; width: 30px; height: 30px; place-items: center; border-radius: 50%; color: var(--color-primary-dark); background: var(--color-primary-soft); }.route-list li > a { display: grid; flex: 1; gap: 5px; }.route-list li span { display: flex; align-items: center; gap: 3px; color: var(--color-muted); font-size: 11px; }.route-list li > button { display: grid; place-items: center; border: 0; color: var(--color-danger); background: transparent; }.modal-backdrop { position: fixed; z-index: 2000; inset: 0; display: grid; place-items: center; padding: 20px; background: rgba(12,25,20,.48); }.delete-modal { width: min(420px,100%); padding: 26px; }.delete-modal > p { color: var(--color-muted); }.delete-modal > div { display: flex; justify-content: flex-end; gap: 7px; margin-top: 20px; }
@media (max-width: 650px) { .course-heading { align-items: start; flex-direction: column; }.course-heading h1 { font-size: 34px; } }
</style>
